# Generated by Django 3.2 on 2021-04-19 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0012_rename_name_montly_expenses_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montly_expenses',
            name='customer',
        ),
        migrations.AddField(
            model_name='montly_expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
